spring.config.import=optional:file:.env[.properties]

spring.application.name=agente-ai-autonomo
server.address=127.0.0.1
server.port=8080

# il valore dummy è temporanea solo per non far crashare pipeline, dato che nel test non viene in utilizzato API Key
google.genai.api-key=${GOOGLE_GENAI_API_KEY:dummy}

google.genai.model=gemini-3.5-flash-lite